# For more information about the configurations used
# in this file, please see the Travis CI documentation:
# http://docs.travis-ci.com

after_success:
  - $(npm bin)/update-branch --commands "npm install && npm run build && git config --global user.email '$user_email' && git config --global user.name '$user_name'"
                             --commit-message "Hey GitHub, this content is for you! [skip ci]"
                             --directory "build" 
                             --distribution-branch "gh-pages"
                             --source-branch "master"


git:
  depth: 5

language: node_js

node_js:
  - "4"

env:
  global:
    - secure: "AAAAB3NzaC1yc2EAAAABJQAAAIEAjcQEfMxuiUJbRCEIGHaiHwM9WF3i+/yfZLsOR0UrVAjekhlQEfBID/1SMzDKtZGh/qvrn1t3cSwgGS5GzbgYzhuZPq4lwNcTgv14UjBIciSMKNxNdjxlPr25JBNgvktKTorD6PeifvZB8ufIs3ro75lrMjixHc/JQdASb126sTM="
